import fs from "node:fs";
import path from "node:path";

const rootDir = process.cwd();
const distDir = path.join(rootDir, "dist");
const outputFile = path.join(distDir, "server.js");
const sourceFiles = [
  "src/errors.js",
  "src/domain.js",
  "src/security.js",
  "src/store.js",
  "src/app.js",
  "src/server.js"
];

const builtinImports = new Set();
const bundledSections = [];

for (const relativeFile of sourceFiles) {
  const absoluteFile = path.join(rootDir, relativeFile);
  let source = fs.readFileSync(absoluteFile, "utf8");

  source = removeImports(source);

  source = source
    .replace(/^export class /gm, "class ")
    .replace(/^export function /gm, "function ")
    .replace(/^export const /gm, "const ");

  bundledSections.push(`// ${relativeFile}\n${source.trim()}\n`);
}

fs.mkdirSync(distDir, { recursive: true });

const output = [
  ...builtinImports,
  "",
  "// This file is generated by scripts/build.js. Do not edit by hand.",
  ...bundledSections
].join("\n");

fs.writeFileSync(outputFile, output);
console.log(`Built ${path.relative(rootDir, outputFile)}`);

function removeImports(source) {
  const lines = source.split("\n");
  const kept = [];
  let skippingImport = false;

  for (const line of lines) {
    const trimmed = line.trim();

    if (skippingImport) {
      if (trimmed.endsWith(";")) skippingImport = false;
      continue;
    }

    if (trimmed.startsWith("import ")) {
      if (trimmed.includes(" from \"node:")) {
        builtinImports.add(line);
      }
      if (!trimmed.endsWith(";")) skippingImport = true;
      continue;
    }

    kept.push(line);
  }

  return kept.join("\n");
}
